version = 0.1

[default.deploy.parameters]
stack_name = "inline-lambda-py"
resolve_s3 = true
s3_prefix = "inline-lambda-py"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-west-2"
